language: ruby
cache: bundler
sudo: false

stages:
  ###  - check
  ###  - spec
  - name: deploy
    if: 'tag IS present'

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

rvm:
  - 2.4.4

jobs:
  include:
    ###  Testing on Travis CI is indefinitely disabled
    ###
    ###  See:
    ###    * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
    ###    * https://simp-project.atlassian.net/browse/SIMP-8703
    ###
    ###    - stage: check
    ###      script:
    ###        - bundle exec rake pkg:create_tag_changelog
    ###
    ###    - stage: spec
    ###      sudo: required
    ###      services:
    ###        - docker
    ###      script:
    ###        - bundle exec rake pkg:rpm
    ###        - bundle exec rake clean

    - stage: deploy
      script:
        - true
      before_deploy:
        - export VERSION=`ruby -ryaml -e "puts YAML.load_file('build/sources.yaml')['version']"`
        - "[[ $TRAVIS_TAG =~ ^${VERSION}$ ]]"

      deploy:
        provider: releases
        api_key:
          secure: m2y7ZVKZAjp5IGdJF3l9phYDthBwDWG89eY/1csPHlTl4s6zrdnQD1Uc6+xmaW3ATyj8btk9ye/FdA9TMNSl1RL1+oCxeBW32phiaRj0aIRr7C08R0i8GHr0zShKkb14F3us8wSzMkKjRgaq5Bm3dhH2vJhNdfGRIGjXgxHvH/rDlF3m5jjgqZizt5Xo8mQgCDlD7uFpqCjM8GmMxKZYsIHSvpEgkGG4inbRXCgBJW41/wT0XaMkpJ+VaQwRaKr7CiVwAGqMbbhgQ0J460z83RedQq8AtMmCH5PjXaStSc3RYHrfUZez+EUqUfUsiYWDvWjO3Xlsebzrx5YCVMYQQL3YatWfKYX2fMrXazmKa2UdEfUTyZREgjyssm53sxPKm4H0QCmY7zNbUpFSt6MuoHmJoezFTj3DX96UikLmm7fysfi+CA8NGalPDb6wZ71WlJDd6uH/fOKhzYzT2UfUGMzYtDnXPSvYDhdmotOBAhAyQ2mfGCjo/DR3HuN68rHJRemzurEcrEBwq4S9CsOtUj2T8MSuJPkTUQqLeS5w1ONjYQazooV9k/knJIasLjl2L5JX/y8FKtVnmRJGf0J24t58MAZUNYQr83bH6tTZxGYoGsonHsipTasd5JIgUgONMLpoi/05m6MYYKhOuv+rPdXvDIyfCExeLsRQevRxAa8=
        on:
          tags: true
          condition: "($SKIP_PUBLISH != true)"
